### ISSUE TITLE
Override the user.auth service in ldap_authentication to do the password check

### ISSUE THREAD

**Issue by larowlan** [Laudanum/ldap#11]
Drupal 8 has a new `UserAuthInterface` that is responsible for checking a username and password and returning a matching `$uid` if the authentication was a success.

See `Drupal\user\UserAuth`.

Ldap auth module should override this service using a `ServiceProvider` and substitute it's own, deferring to the parent implementation as necessary for fallback sake.

**Comment by queenvictoria** [comment]
```
[1:50pm] larowlan: so you need a ServiceProvider
[1:51pm] larowlan: that alters user.auth to use an ldap provider
[1:51pm] larowlan: that extends from UserAuth
[1:51pm] larowlan: it tries to authenticate agains ldap
[1:51pm] larowlan: and if it fails
[1:51pm] larowlan: defers back to parent
[1:51pm] larowlan: so that user 1 can still login when ldap is down etc
```

**Comment by larowlan** [comment]
A sample service provider https://github.com/md-systems/file_entity/blob/8.x-2.x/src/FileEntityServiceProvider.php
And there's a write up by some gumby here https://www.previousnext.com.au/blog/overriding-services-drupal-8-advanced-cases

**Comment by queenvictoria** [comment]
Notes from John Barclay
"""
In this area, your best allies/sources of code for ldap authentication are any other authentication module that is developing for Drupal 8 or the core user module and openid module.

 You just need to look at a module one that *uses credentials entered directly* into Drupal and one that uses *external server for users authentication* such shib or a saml module.  The core user module and openid modules did this in Drupal 7 and may also be good to imitate in drupal 8.  In drupal 7, I could not imitate them because of (1) a bug in the user module, (2) because I tried to put both types of authentication in one module, and (3) because I had to create user accounts on the fly on logon. 
"""

**Comment by webflo** [comment]
I found https://www.drupal.org/project/externalauth yesterday.

**Comment by queenvictoria** [comment]
Thanks @webflo . I've had a quick email exchange with @svendecabooter about the module you mention. I'm going to try and catch him this afternoon or during the next few days to discuss possible cross overs or integrations with LDAP. Here are his comments.

"""
The module came about when porting the https://www.drupal.org/project/simplesamlphp_auth module to Drupal 8.
It's an attempt to create a generic solution for the problems that were solved in Drupal 7 core with regards to external login.
It would indeed be interesting to see if the module can be used for the LDAP module in Drupal 8.
"""
@svendecabooter

**Comment by queenvictoria** [comment]
@svendecabooter
queenvictoria: `simplesamlphp_auth/src/Service/SimplesamlphpDrupalAuth.php` adds the externalauth service, which could be useful as an example

**Comment by queenvictoria** [comment]
The outcome of the conversation is that externalauth pretty much just provides the authmap table that was removed from core in D8. It provides other bits and pieces. @svendecabooter is happy to receive patches for other functionality. I will rework ldap_authenication to use externalauth where possible (at least the authmap table).

**Comment by queenvictoria** [comment]
Closed in favour of https://www.drupal.org/node/2698157
